# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/rablab/showcase/models/category/columns.yaml

# Model Class name
modelClass: RabLab\Showcase\Models\Category

# List Title
title: Manage Showcase Categories

# Link URL for each record
recordUrl: rablab/showcase/categories/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 15

# Sort by
defaultSort: name

# Display checkboxes next to each record
# showCheckboxes: yes

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



